In [2]:
import os
os.chdir(r'G:\Ext_Disk_SharedFolder\Career\Oracle\ADW Challenge - Candidate Pack')
os.getcwd()
import pandas as pd
Warehouse = pd.read_excel('PCW15 D Warehouse.xlsx')

In [3]:
Warehouse.shape

(12, 9)

In [4]:
Warehouse

,Store Id,Warehouse Id,Warehouse,Min Ship Time,Max Ship Time,WH Street,WH State,WH City,WH Zip
0,1,WH 1,City of Industry,1,2,464-498 N Sunset Ave,CA,La Puente,91744
1,2,WH 1,City of Industry,1,4,464-498 N Sunset Ave,CA,La Puente,91744
2,3,WH 1,City of Industry,1,5,464-498 N Sunset Ave,CA,La Puente,91744
3,4,WH 2,Reading,1,3,84 Woburn St,MA,Reading,1867
4,5,WH 2,Reading,1,3,84 Woburn St,MA,Reading,1867
5,6,WH 2,Reading,1,3,84 Woburn St,MA,Reading,1867
6,7,WH 3,Newark,1,3,414 Raymond Blvd,NJ,Newark,7105
7,8,WH 3,Newark,1,3,414 Raymond Blvd,NJ,Newark,7105
8,9,WH 3,Newark,1,3,414 Raymond Blvd,NJ,Newark,7105
9,10,WH 4,Upper NY,1,3,2157 East Ave,NY,Rochester,14610
10,11,WH 4,NYC,1,2,1263 Dean St,NY,Brooklyn,11216
11,12,WH 4,Upper NY,1,3,2157 East Ave,NY,Rochester,14610